rd /s /q "d:\documents\docs\tutorial-basics"
rd /s /q "d:\documents\docs\tutorial-extras"
del "d:\documents\docs\intro.md"
del "d:\documents\docs\introduction\why-aurelic-exists.md"
del "d:\documents\docs\introduction\who-is-this-for.md"
mkdir "d:\documents\docs\introduction\why-veilfi-exists"
mkdir "d:\documents\docs\introduction\who-is-this-for"
mkdir "d:\documents\docs\core-concepts\key-concepts-definitions"
mkdir "d:\documents\docs\core-concepts\core-principles"
mkdir "d:\documents\docs\core-concepts\credit-model-overview"
mkdir "d:\documents\docs\protocol-design\architecture-overview"
mkdir "d:\documents\docs\protocol-design\modular-components"
mkdir "d:\documents\docs\protocol-design\capital-flow-model"
mkdir "d:\documents\docs\core-flow\lender-flow"
mkdir "d:\documents\docs\core-flow\borrower-flow"
mkdir "d:\documents\docs\core-flow\liquidation-flow"
mkdir "d:\documents\docs\key-features"
mkdir "d:\documents\docs\technical-details\smart-contract-architecture"
mkdir "d:\documents\docs\technical-details\permission-governance-model"
mkdir "d:\documents\docs\technical-details\security-considerations"
mkdir "d:\documents\docs\frontend-ux"
mkdir "d:\documents\docs\integration-guide"
mkdir "d:\documents\docs\conclusion"
mkdir "d:\documents\docs\support"
